spring:
  application:
    name: user-service


  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-postgres
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update   # hoặc: none | validate | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # (Tùy chọn) Logging SQL rõ hơn trong console
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# (Tùy chọn) Cấu hình server
server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
  instance:
    hostname: localhost # Tên host của instance này
    # instance-id: ${spring.application.name}:${random.value} # Tùy chọn: tạo ID instance độc nhất

minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin123
  bucketName: joblink
